env:
  browser: true
  es6: true
  node: true
extends:
  - "plugin:react/recommended"
  - airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
plugins:
  - react
  - "@typescript-eslint"
rules: {}
overrides:
  - files: "*.stories.js"
    rules:
      import/no-extraneous-dependencies: 0
      react/jsx-filename-extension: 0
